language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy

install:
    - bash scripts/travis_install.sh
    - pip install coveralls

script:
    - haas okonomiyaki
    - coverage run -a -m haas tests/functional

after_success:
    coveralls

notifications:
    email:
        - davidc@enthought.com
