language: python

env:
  global:
    - PYTHONUNBUFFERED="1"

  - os: linux
    sudo: false
  - os: osx
    osx_image: xcode6.4  # 10.9

python:
  - 2.7
  - 3.5
  - pypy

cache:
  pip: true

branches:
  only:
    - master
    - maint/*

install:
    - bash scripts/travis_install.sh
    - pip install coveralls

script:
    - if [[ ${TRAVIS_OS_NAME} == "linux" ] && [ ${PYTHON} == "2.7" ]]; then flake8 okonomiyaki fi
    - coverage run -m haas okonomiyaki

after_success:
    coveralls

notifications:
    email:
        - davidc@enthought.com
