language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy

install:
    - bash scripts/travis_install.sh

script:
    - nosetests --with-coverage --cover-package=okonomiyaki okonomiyaki

notifications:
    email:
        - davidc@enthought.com
