language: python
python:
   - 2.7
install:
   - pip install nose coverage
script:
  - nosetests --with-coverage --cover-package=okonomiyaki okonomiyaki
notifications:
  email:
    - davidc@enthought.com
