language: python

env:
  global:
    - PYTHONUNBUFFERED="1"

matrix:
  include:
  - os: linux
    sudo: false
    python: 2.7
    env: RUN_FLAKE8="1"
  - os: linux
    sudo: false
    python: 3.5
  - os: linux
    sudo: false
    python: pypy


cache:
  pip: true

branches:
  only:
    - master
    - maint/*

install:
    - bash scripts/travis_install.sh
    - pip install coveralls

script:
    - if [[ ${RUN_FLAKE8} == "1" ]]; then flake8 okonomiyaki; fi
    - coverage run -m haas okonomiyaki

after_success:
    coveralls

notifications:
    email:
        - davidc@enthought.com
