language: python

env:
  global:
    - PYTHONUNBUFFERED="1"

python:
  - 2.7
  - 3.5
  - pypy

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      osx_image: xcode6.4  # 10.9

cache:
  pip: true

branches:
  only:
    - master
    - maint/*

install:
    - bash scripts/travis_install.sh
    - pip install coveralls

script:
    - coverage run -a -m haas okonomiyaki

after_success:
    coveralls

notifications:
    email:
        - davidc@enthought.com
