language: python
python:
   - 2.6
   - 2.7
   - 3.2
   - 3.3
   - pypy
install:
   - if [[ "${TRAVIS_PYTHON_VERSION}" -eq "2.6" ]]; then
       pip install -rdev_requirements_py26.txt;
       else
       env;
       pip install -rdev_requirements.txt;
       fi
   - pip install .
script:
  - nosetests --with-coverage --cover-package=okonomiyaki okonomiyaki
notifications:
  email:
    - davidc@enthought.com
