language: python
python:
   - 2.6
   - 2.7
   - 3.3
   - pypy
install:
   - pip install -rdev_requirements.txt
   - pip install .
script:
  - nosetests --with-coverage --cover-package=okonomiyaki okonomiyaki
notifications:
  email:
    - davidc@enthought.com
