language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - pypy

before_install:
    - sudo apt-get update
    - sudo apt-get install python3.4

install:
    - bash scripts/travis_install.sh

script:
    - nosetests --with-coverage --cover-package=okonomiyaki okonomiyaki

notifications:
    email:
        - davidc@enthought.com
