build: false
skip_branch_with_pr: true
platform: x64

environment:

  global:
    PYTHONUNBUFFERED: "1"
    LANG: "ENG"

  matrix:
    - python: "C:/Python27-x64"
    - python: "C:/Python27"
    - python: "C:/Python35-x64"
    - python: "C:/Python35"
    - python: "C:/Python36-x64"
    - python: "C:/Python36"
    - python: "C:/Python38-x64"
    - python: "C:/Python38"

branches:
  only:
  - master
  - /^maintenance\/.*$/

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

matrix:
  fast_finish: true

init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path

install:
  - cmd: python -m pip install --upgrade pip wheel
  - cmd: pip --version
  - cmd: pip install .
  - cmd: pip install -r dev_requirements.txt
test_script:
  - cmd: cd jenkins
  - cmd: coverage run -m haas okonomiyaki
