User Guide
----------

This part of the documentation focuses on step-by-step instructions for getting
the most out of the library.

.. toctree::
   :maxdepth: 2

   user/quickstart

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

File formats
------------

If you are looking for information about a specific file format, like our egg
or runtime packaging format, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   file_formats
