User Guide
----------

This part of the documentation focuses on step-by-step instructions for getting
the most out of the library.

.. toctree::
   :maxdepth: 2

   user/quickstart

Dev Guide
---------

This part of the documentation explains the main concepts of okonomiyaki.

.. toctree::
   :maxdepth: 2

   examples

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api
