name: okonomiyaki

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        python-version: [2.7, 3.6]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install okonomiyaki
      run: |
        python -m pip install .
    - name: Install test dependencies
      run: python -m pip install -r "dev_requirements.txt"
    - name: Test with haas
      run: python -m haas okonomiyaki
